apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roms
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn 
  resources:
    requests:
      storage: 128Mi
