{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "game.fullname" . }}
  namespace: games
spec:
  secretName: {{ include "game.fullname" . }}-cert-secret        # <===  Name of secret where the generated certificate will be stored.
  dnsNames:
    - "{{ include "game.fullname" . }}"
  issuerRef:
    name: hobo-intermediate-ca1-issuer
    kind: ClusterIssuer
{{- end }}
